[package]
name = "bcdk"
version = "0.1.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Biyard canister development kit"
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/bcdk"

[dependencies]
ic-cdk.workspace = true
ic-cdk-timers.workspace = true
candid.workspace = true
serde.workspace = true
serde_json.workspace = true
