[book]
authors = ["biyard"]
language = "en"
multilingual = false
src = "docs"
title = "Biyard Development Documentation"

[rust]
edition = "2021"

[build]
build-dir = ".build/docs"

[output.html]
mathjax-support = true

[output.html.playground]
editable = true

