[package]
name = "btracing"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository = "https://github.com/biyard/rust-sdk/tree/main/packages/btracing"

[dependencies]
dioxus.workspace = true
gloo-timers = { version = "0.3.0", features = ["futures"] }
tracing = "0.1.41"
